# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heating.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heating.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rheating.proto\x12\x11heatingprediction\"e\n\x0fHeatingFeatures\x12\x0e\n\x06Hubids\x18\x01 \x01(\x02\x12\x0f\n\x07\x45ircode\x18\x02 \x01(\t\x12\r\n\x05Month\x18\x03 \x01(\x02\x12\x11\n\tTwoHrSlot\x18\x04 \x01(\x02\x12\x0f\n\x07gas_pct\x18\x05 \x01(\x02\"O\n\x11HeatingPrediction\x12\x1b\n\x13predicted_heat_mean\x18\x01 \x01(\x02\x12\r\n\x05\x61lert\x18\x02 \x01(\t\x12\x0e\n\x06tariff\x18\x03 \x01(\t2m\n\x0eHeatingPredict\x12[\n\x0fpredict_heating\x12\".heatingprediction.HeatingFeatures\x1a$.heatingprediction.HeatingPredictionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heating_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEATINGFEATURES']._serialized_start=36
  _globals['_HEATINGFEATURES']._serialized_end=137
  _globals['_HEATINGPREDICTION']._serialized_start=139
  _globals['_HEATINGPREDICTION']._serialized_end=218
  _globals['_HEATINGPREDICT']._serialized_start=220
  _globals['_HEATINGPREDICT']._serialized_end=329
# @@protoc_insertion_point(module_scope)
